
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "!0283>,l;KJi+_)%$3"
      MYSQL_DATABASE: thedatabaseskillmatch
    volumes:
      - mysql_data:/var/lib/mysql

  skillmatch-api:
    build: ./SkillMatch
    container_name: skillmatch-api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_KEY: base64:Ps5IGofgjEQ24CyplMRXyxgcgIjebuysFkc6X2TDsxg=
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: thedatabaseskillmatch
      DB_USERNAME: root
      DB_PASSWORD: "!0283>,l;KJi+_)%$3"

  skillmatch-frontend:
    build: ./skillmatch-front-end
    container_name: skillmatch-frontend
    ports:
      - "3000:3000"

  training-app:
    build: ./training_app
    container_name: training-app
    ports:
      - "4200:3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - skillmatch-api
      - skillmatch-frontend
      - training-app

volumes:
  mysql_data:
