
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - skillmatch-api
      - skillmatch-frontend
      - training-app

  skillmatch-api:
    build: ./SkillMatch
    container_name: skillmatch-api
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - DB_HOST=host.docker.internal  # for macOS/Windows
      - DB_PORT=3306
      - DB_DATABASE=skillmatch
      - DB_USERNAME=root
      - DB_PASSWORD=your_db_password_here

  skillmatch-frontend:
    build: ./skillmatch-front-end
    container_name: skillmatch-frontend
    ports:
      - "3000:3000"

  training-app:
    build: ./training_app
    container_name: training-app
    ports:
      - "4200:3000"
